# Generated by Django 3.1.3 on 2020-11-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20201117_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='companies',
            field=models.ManyToManyField(related_name='companies', to='company.Company'),
        ),
    ]
